datasources.default.db-type=mysql
datasources.default.dialect=MYSQL
micronaut.application.name=icr-church
jpa.default.properties.hibernate.hbm2ddl.auto=update
datasources.default.driver-class-name=com.mysql.cj.jdbc.Driver
datasources.default.password=root
datasources.default.url=jdbc:mysql://localhost:3306/icr
datasources.default.username=root
jpa.default.properties.hibernate.show_sql=true
jpa.default.entity-scan.packages=com.devhouse
jackson.property-naming-strategy=SNAKE_CASE
file.storage.base-path=/public


micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.web.max-age=0
micronaut.server.cors.configurations.web.allowed-origins[0]=http://localhost:5173
micronaut.server.cors.configurations.web.allowed-origins[1]=http://frontend:5173
micronaut.server.cors.configurations.web.allowed-methods[0]=GET
micronaut.server.cors.configurations.web.allowed-methods[1]=POST
micronaut.server.cors.configurations.web.allowed-methods[2]=PUT
micronaut.server.cors.configurations.web.allowed-methods[3]=DELETE
micronaut.server.cors.configurations.web.allowed-methods[4]=OPTIONS
micronaut.server.cors.configurations.web.allowed-methods[5]=HEAD
micronaut.server.cors.configurations.web.allowed-methods[6]=PATCH
micronaut.server.cors.configurations.web.allowed-headers[0]=Content-Type
micronaut.server.cors.configurations.web.allowed-headers[1]=Authorization
micronaut.server.cors.configurations.web.allow-credentials=true
