datasources.default.db-type=mysql
datasources.default.dialect=MYSQL
micronaut.application.name=icr-church
jpa.default.properties.hibernate.hbm2ddl.auto=update
datasources.default.driver-class-name=com.mysql.cj.jdbc.Driver
datasources.default.password=root
datasources.default.url=jdbc:mysql://localhost:3306/icr
datasources.default.username=root
jpa.default.properties.hibernate.show_sql=true
jpa.default.entity-scan.packages=com.devhouse
jackson.property-naming-strategy=SNAKE_CASE
file.storage.base-path=/public

